name: 'NodeJS Upload Asset'
description: 'Upload asset'
author: 'Gregor Anders <gregor.ander@gmail.com>'
inputs:
  id:
    description: 'Release ID'
    required: true
  path:
    description: 'Release Asset Path'
    required: true
  label:
    description: 'Release Asset Label'
    required: false
  name:
    description: 'Release Asset File Name'
    required: false
outputs:
  id:
    description: 'Asset Id'
  url:
    description: 'Asset Download Url'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'package'
  color: 'red'
